"""Product-owned numeric limits for the replenishment JSON contract."""

JSON_SAFE_INTEGER_MAX = (1 << 53) - 1
MAX_REPLENISHMENT_ITEM_COUNT = 100
MAX_INVENTORY_UNIT_VALUE = JSON_SAFE_INTEGER_MAX // (
    2 * MAX_REPLENISHMENT_ITEM_COUNT
)
MAX_DERIVED_ITEM_UNIT_VALUE = 2 * MAX_INVENTORY_UNIT_VALUE
